import { invoiceType, itemsType } from "@/types/table";

export const exampleDataInvoice = [
  {
    id: 1,
    invoice_number: "BDG-023568",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Budi - Admin Bandung",
    notes: "Transfer Bu Susi",
  },
  {
    id: 2,
    invoice_number: "JKT-101879",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Tono - Admin Jakarta",
    notes: "Transfer Bu Susi",
  },
  {
    id: 3,
    invoice_number: "SBY-000492",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Asep - Admin Surabaya",
    notes: "Transfer Bu Susi",
  },
  {
    id: 1,
    invoice_number: "BDG-023568",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Budi - Admin Bandung",
    notes: "Transfer Bu Susi",
  },
  {
    id: 2,
    invoice_number: "JKT-101879",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Tono - Admin Jakarta",
    notes: "Transfer Bu Susi",
  },
  {
    id: 3,
    invoice_number: "SBY-000492",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Asep - Admin Surabaya",
    notes: "Transfer Bu Susi",
  },
  {
    id: 1,
    invoice_number: "BDG-023568",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Budi - Admin Bandung",
    notes: "Transfer Bu Susi",
  },
  {
    id: 2,
    invoice_number: "JKT-101879",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Tono - Admin Jakarta",
    notes: "Transfer Bu Susi",
  },
  {
    id: 3,
    invoice_number: "SBY-000492",
    customer_name: "John Doe",
    date: new Date(),
    items: [
      {
        item_name: "Pololinen",
        color: 120,
        roll: 2,
        yards: [90, 10],
        price: 57500,
        sub_total: 5750000,
      },
      {
        item_name: "Pololinen",
        color: 94,
        roll: 3,
        yards: [25, 40, 35],
        price: 30000,
        sub_total: 3000000,
      },
      {
        item_name: "Pololinen",
        color: 10,
        roll: 4,
        yards: [10, 65, 10, 15],
        price: 40000,
        sub_total: 4000000,
      },
    ],
    total_color: 3,
    total_roll: 9,
    total_yard: 300,
    grand_total: 12750000,
    status: "LUNAS",
    created_by: "Asep - Admin Surabaya",
    notes: "Transfer Bu Susi",
  },
];

export const exampleDataItems = [
  {
    id: 1,
    updated_date: new Date(),
    name: "Pololinen",
    roll: 100,
    color_code: 3,
    color_name: "Black",
  },
  {
    id: 2,
    updated_date: new Date(),
    name: "Rayon Twill",
    roll: 200,
    color_code: 5,
    color_name: "Red",
  },
  {
    id: 3,
    updated_date: new Date(),
    name: "Babydoll",
    roll: 50,
    color_code: 7,
    color_name: "Green",
  },
  {
    id: 4,
    updated_date: new Date(),
    name: "Cey",
    roll: 75,
    color_code: 2,
    color_name: "Blue",
  },
  {
    id: 5,
    updated_date: new Date(),
    name: "Turkish Linen",
    roll: 20,
    color_code: 13,
    color_name: "White",
  },
  {
    id: 1,
    updated_date: new Date(),
    name: "Pololinen",
    roll: 100,
    color_code: 3,
    color_name: "Black",
  },
  {
    id: 2,
    updated_date: new Date(),
    name: "Rayon Twill",
    roll: 200,
    color_code: 5,
    color_name: "Red",
  },
  {
    id: 3,
    updated_date: new Date(),
    name: "Babydoll",
    roll: 50,
    color_code: 7,
    color_name: "Green",
  },
  {
    id: 4,
    updated_date: new Date(),
    name: "Cey",
    roll: 75,
    color_code: 2,
    color_name: "Blue",
  },
  {
    id: 5,
    updated_date: new Date(),
    name: "Turkish Linen",
    roll: 20,
    color_code: 13,
    color_name: "White",
  },
];
